### ISSUE TITLE
[WeGiveYouEat] - Add functionality to new post screen

### ISSUE THREAD

**Issue by csham420** [imraminradmand/WeGiveYouEat#14]
## Description

Posting Details page should be made in coherence with the format and features that are present in the figma file.

## User Acceptance Criteria

- Images of the food/drinks being posted --> ONLY ALLOW SINGLE IMAGE UPLOAD
- A title for the specific post
- User provided details regarding the food/drinks

**Need to be posted to the DB**

**Comment by imraminradmand** [comment]
@csham420 has added all possible functionality here, closing as this will now need to be paused till api error is fixed. All requirements for this issue has been met.
