### ISSUE TITLE
[WeGiveYouEat] - Create Figma design 

### ISSUE THREAD

**Issue by imraminradmand** [imraminradmand/WeGiveYouEat#4]
## Description
Create a UI design for app
## User Acceptance Criteria
 * Start-up page
 * Main page
 * Filter view
 * Account signup 
 * Details page
## Anything assignee should take into consideration?
 * N/A

**Comment by danzola01** [comment]
Link to Figma project [here](https://www.figma.com/file/V6NtbVHuHiEn3eHFGZFaOG/We-Give-You-Eat?node-id=9%3A34)
